spring:
  cloud:
    stream:
#      bindings:
#        generateThreeOrderTypes-out-0:
#          destination: ordertopic
#          content-type: application/json
#          
#        functionRouter-in-0:
#          destination: ordertopic
#          content-type: application/json
#        
#        readOrder-in-0: 
#          destination: orderprocessor
#          content-type: application/json
      function:
        routing:
          enabled: true

    function:
      definition: generateThreeOrderTypes;readINDOrder;readUSAOrder
      routing-expression: "headers['orderCountry'] == 'IND' ? 'readINDOrder' : 'readUSAOrder'"
      
      
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672   
    
   